### ISSUE TITLE
Question : How to turn datetime object into string?

### ISSUE THREAD

**Issue by ghost** [hmason/datastorytelling#7]
I am trying to sort out by this order. 
#1. Find all restaurants near NYU( zipcode: 10003)
#2. create variables to store score, currentGrade, and grade Date.
#3. remove restaurants list that has : score under average, current grade is not A, and

```
                                                            grade date is out of date. 
```

In this process, I couldn't turn datetime object into string, which makes impossible to 
evaluate the date time object. ( I know there is a way to do it, but still can't figure it out)
- I also want to use violcode as filter, but can't figure out what the data means..

**Comment by hmason** [comment]
If you just need any string you can cast it like this:

```
t = datetime.datetime.now()
str(t)
```

And if you need a particular string format you can also use the strftime() function:

```
t.strftime('%Y')
```

...but why do you need a string?

**Comment by ghost** [comment]
Thanks for the info, I was able to find reference in python and changed the datetime object to string. 
The reason why I wanted to convert the datatime object into string is that  I tried to check if the restaurants have been graded recently or not. Otherwise, I assume that they don't have validate grade on their food. 

And I got the result based on my filter :). 

I evalute all restaurants in data.

There are 12 good restaurants near NYU

They have A grade, and recently got high score on their food

Here are the lists of restaurants

Name of restaurant : MCDONALD'S, Score :3, Grade : A
Name of restaurant : MCDONALD'S, Score :2, Grade : A
Name of restaurant : BLUE 9 BURGER, Score :5, Grade : A
Name of restaurant : BLUE 9 BURGER, Score :5, Grade : A
Name of restaurant : CLARKE'S STANDARD, Score :7, Grade : A
Name of restaurant : CLARKE'S STANDARD, Score :7, Grade : A
Name of restaurant : MCDONALD'S, Score :7, Grade : A
Name of restaurant : MCDONALD'S, Score :5, Grade : A
Name of restaurant : MCDONALD'S, Score :7, Grade : A
Name of restaurant : BURGER CREATIONS, Score :8, Grade : A
Name of restaurant : POPS, Score :7, Grade : A
Name of restaurant : POPS, Score :7, Grade : A

Not surprisingly, mcDonald is the one of the top place to go near NYU in term of score, grade...

**Comment by hmason** [comment]
Ha!
